### ISSUE TITLE
/link for players having space in usernames

### ISSUE THREAD

**Issue by Infernus101** [poggit-orphanage/SimpleAuth#4]
I am using namecorrector so the spaces in a player's usernames gets converted to underscores, and when they do /link and relogin the username doesnt get changed to the linked username since its being converted by namecorrector too, i was hoping if you could make it compatible with namecorrector...

**Comment by Awzaw** [comment]
I'll look into it, but why use name corrector when PocketMine now handles spaces in names?

**Comment by Infernus101** [comment]
It does?

**Comment by Awzaw** [comment]
Yes, and you just use quotes around player names, so `/op "awzaw jdn"`, for example.

**Comment by Infernus101** [comment]
Um so in voterewards plugin {player} wont work in commands section?
